SELECT * FROM supermarket;

--(1) Total Revenue Generated by Supermarket Company
   SELECT SUM(Total) AS Total_revenue FROM supermarket;

--(2) Total Quantity of Product sold by Supermarket Company
    SELECT SUM(Quantity) AS Total_quantity FROM supermarket;

--(3) Gross Income Generated by Supermarket Company
	SELECT SUM([gross income]) AS Gross_income FROM supermarket;

--(4) Average Rating of Supermarket Company
    SELECT AVG(Rating) AS Average_rating FROM supermarket;
	
--(5) Total number of customers
	SELECT COUNT([Invoice ID]) AS No_of_customers FROM supermarket;

--(6) Which branch Generated the largest Gross income
     SELECT Branch, SUM([gross income]) AS GrossIncome
	 FROM supermarket
	 GROUP BY Branch  
	 ORDER BY GrossIncome DESC;

--(7) Which product line had the most sales
	SELECT TOP 1 [product line], SUM([Quantity]) AS Total_Quantity
	FROM supermarket
	GROUP BY [product line]
	ORDER BY Total_Quantity DESC;

--(8) How much gross income was made from each product line
   (SELECT [product line],SUM([gross income]) AS Grossincome
   FROM supermarket
   GROUP BY [product line])
   ORDER BY Grossincome DESC;

--(9) Number of customers per payment method
	SELECT Payment, (COUNT([invoice id]) / COUNT(DISTINCT[Payment])) AS NO_of_customer 
	FROM supermarket 
	GROUP BY payment 
	ORDER BY NO_of_customer DESC;

--(10) Customer Distribution per gender
	SELECT Gender, COUNT(Gender) / COUNT(DISTINCT(Gender)) AS Total
	FROM supermarket
	GROUP BY Gender
	ORDER BY Total DESC;

--(11) Gross income by customer type
   SELECT Gender, COUNT([Customer type]) / COUNT(DISTINCT([Customer type])) AS Total
   FROM supermarket
   GROUP BY Gender
   ORDER BY Total DESC;

--(12) Gross Income per month
	SELECT month(Date) AS month_of_year, SUM([gross income]) AS Grossincome
	FROM supermarket
	group by month(Date)
	order by Grossincome DESC;

--(13) Average rating per product line
	SELECT [product line], AVG(rating) as Average_Rating
	FROM supermarket
	GROUP BY [product line]
	ORDER BY Average_Rating DESC;

